#!/usr/bin/python

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import re

driver = webdriver.Firefox()
driver.get('https://www.facebook.com/login.php')

username = driver.find_element_by_id("email")
password = driver.find_element_by_id("pass")

username.send_keys('uukaran1@gmail.com')
password.send_keys('Chr0n!cl3')

driver.find_element_by_name("login").click()

pattern = "[Hrishika]"
compiled = re.compile(pattern)

while True:
    msg_noti = driver.find_element_by_id('mercurymessagesCountValue')
    if msg_noti.text=='' or msg_noti.text==0:
        continue
    elif msg_noti.text>0:
        msg_noti.click()
        unread = driver.find_elements_by_class_name('jewelItemNew')
        for msgs in unread:
            match = re.findall(compiled , msgs.text)
            if len(match)<8:
                continue
            else:
                string = ''
                for i in range (0,8):
                    string = string + match[i]
                driver.get('https://www.facebook.com/messages/100002427137739')
                body = driver.find_element_by_name("message_body")
                body.send_keys("This Message is automatically generated by a script desgined by your SMART PD *ME*. I am not currently available and will reply you back as soon as i'll check my account. Love u .... :* \n")
                driver.get('https://www.facebook.com/')
